apiVersion: v1
kind: ServiceAccount
metadata:
  name: centraldashboard
  namespace: kubeflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centraldashboard
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: centraldashboard
    app.kubernetes.io/version: "1.8.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: centraldashboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: centraldashboard
    spec:
      serviceAccountName: centraldashboard
      containers:
      - name: centraldashboard
        image: kubeflownotebookswg/centraldashboard:v1.8.0
        ports:
        - containerPort: 8082
        env:
        - name: USERID_HEADER
          value: "kubeflow-userid"
        - name: USERID_PREFIX
          value: ""
        - name: PROFILES_KFAM_SERVICE_HOST
          value: "profiles-kfam.kubeflow"
        - name: PROFILES_KFAM_SERVICE_PORT
          value: "8081"
        - name: REGISTRATION_FLOW
          value: "false"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: centraldashboard
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: centraldashboard
spec:
  selector:
    app.kubernetes.io/name: centraldashboard
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-deployment
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: profiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: profiles
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profiles
    spec:
      containers:
      - name: manager
        image: kubeflownotebookswg/profile-controller:v1.8.0
        ports:
        - containerPort: 8080
        env:
        - name: USERID_HEADER
          value: "kubeflow-userid"
        - name: USERID_PREFIX
          value: ""
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: profiles-kfam
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: profiles
spec:
  selector:
    app.kubernetes.io/name: profiles
  ports:
  - port: 8081
    targetPort: 8080
    protocol: TCP