apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline
  namespace: kubeflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: ml-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-pipeline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ml-pipeline
    spec:
      serviceAccountName: ml-pipeline
      containers:
      - name: ml-pipeline-api-server
        image: gcr.io/ml-pipeline/api-server:2.0.5
        ports:
        - containerPort: 8888
        - containerPort: 8887
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OBJECTSTORECONFIG_SECURE
          value: "false"
        - name: OBJECTSTORECONFIG_BUCKETNAME
          value: "mlpipeline"
        - name: MINIO_SERVICE_SERVICE_HOST
          value: "minio-service"
        - name: MINIO_SERVICE_SERVICE_PORT
          value: "9000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: ml-pipeline
spec:
  selector:
    app.kubernetes.io/name: ml-pipeline
  ports:
  - name: http
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: grpc
    port: 8887
    targetPort: 8887
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: ml-pipeline-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-pipeline-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ml-pipeline-ui
    spec:
      containers:
      - name: ml-pipeline-ui
        image: gcr.io/ml-pipeline/frontend:2.0.5
        ports:
        - containerPort: 3000
        env:
        - name: ML_PIPELINE_SERVICE_HOST
          value: "ml-pipeline"
        - name: ML_PIPELINE_SERVICE_PORT
          value: "8888"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: ml-pipeline-ui
spec:
  selector:
    app.kubernetes.io/name: ml-pipeline-ui
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-10-25T06-33-25Z
        args:
        - server
        - /data
        ports:
        - containerPort: 9000
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: kubeflow
  labels:
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP